services:
  - type: web
    name: agro-backend
    env: node
    repo: https://github.com/Fark04/Agro
    branch: main
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "node server.js"
    autoDeploy: true

  - type: web
    name: agro-frontend
    env: static
    repo: https://github.com/Fark04/Agro
    branch: main
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    startCommand: "npx serve -s dist"
    autoDeploy: true

  - type: web
    name: agro-nginx
    env: docker
    repo: https://github.com/Fark04/Agro
    branch: main
    rootDir: nginx
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
